# Generated by Django 4.0.4 on 2022-05-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0002_userhandinput_usergadgetinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='UserGagetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apidata', models.CharField(max_length=30)),
                ('gagetinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.usergadgetinfo')),
            ],
        ),
    ]
