# Generated by Django 4.0.4 on 2022-05-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0003_userfileupload_file_usergagetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
